#! /bin/bash

../../tools/duic/duic bookmarks.ui -o ui_bookmarks.d
../../tools/duic/duic addbookmarkdialog.ui -o ui_addbookmarkdialog.d
../../tools/duic/duic addbookmarkdialog.ui -o ui_addbookmarkdialog.d
../../tools/duic/duic cookiesexceptions.ui -o ui_cookiesexceptions.d
../../tools/duic/duic cookies.ui -o ui_cookies.d
../../tools/duic/duic downloaditem.ui -o ui_downloaditem.d
../../tools/duic/duic downloads.ui -o ui_downloads.d
../../tools/duic/duic history.ui -o ui_history.d
../../tools/duic/duic passworddialog.ui -o ui_passworddialog.d
../../tools/duic/duic proxy.ui -o ui_proxy.d
../../tools/duic/duic settings.ui -o ui_settings.d

ldc *.d -L-L../../lib -L-lqtdgui -L-lqtdcore -I../../ -I../../qt/d1 -L-lQtGui -L-lQtCore -ofbrowser
